BROKER_URL = "PLAINTEXT://localhost:9092"
REST_PROXY_URL = "http://localhost:8082"
SCHEMA_REGISTRY_URL = "http://localhost:8081"
KAFKA_CONNECT_URL = "http://localhost:8083"
KSQL_URL = "http://localhost:8088"
POSTGRESQL_URL = "jdbc:postgresql://localhost:5432/cta"
